#########################################################
# @file       .travis.yml
# @brief      The settings for Travis CI
# @author     dragon-archer <dragon-archer@outlook.com>
# @since      v0.1
# @license    The MIT License
#             Copyright (C) 2019 dragon-archer
#########################################################

language: cpp
sudo: required
dist: bionic
compiler:
- g++
os:
- linux
script:
- mkdir build && cd build
- cmake .. -G "Unix Makefiles"
branches:
  only:
  - master
  - develop
notifications:
  email: false
