#########################################################
# @file       azure-pipelines.yml
# @brief      The settings for Azure Pipelines CI
# @author     dragon-archer <dragon-archer@outlook.com>
# @since      v0.1
# @license    The MIT License
#             Copyright (C) 2019 dragon-archer
#########################################################

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir build
    cd build
    cmake ..
  displayName: 'Build Makefile by CMake'
- script: |
    cd build
    make
  displayName: 'Build the project by GNU Make'