#########################################################
# @file       azure-pipelines.yml
# @brief      The settings for Azure Pipelines CI
# @author     dragon-archer <dragon-archer@outlook.com>
# @since      v0.1
# @license    The MIT License
#             Copyright (C) 2019 dragon-archer
#########################################################

trigger:
- master
- develop

jobs:
- job: Build in Windows Server 2019
    vmImage: 'windows-2019'
    steps:
    - script: |
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles"
        nmake
      displayName: 'Build Makefile by CMake ; Build the project by NMake'
- job: Build in Ubuntu 16.04
    vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        mkdir build
        cd build
        cmake .. -G "Unix Makefiles"
        make
      displayName: 'Build Makefile by CMake ; Build the project by GNU Make'

