#########################################################
# @file       azure-pipelines.yml
# @brief      The settings for Azure Pipelines CI
# @author     dragon-archer <dragon-archer@outlook.com>
# @since      v0.1
# @license    The MIT License
#             Copyright (C) 2019 dragon-archer
#########################################################

trigger:
- master
- develop

jobs:
- job: build_in_windows_2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      mkdir build
      cd build
      cmake .. -G "MinGW Makefiles"
      mingw32-make
      mingw32-make clean
      cd ..
      rm -rf build/
    displayName: 'Build Makefile by CMake & Build project by GNU Make'
  - script: |
      mkdir build
      cd build
      cmake .. -G "NMake Makefiles"
      nmake
      nmake clean
      cd ..
      rm -rf build/
    displayName: 'Build Makefile by CMake & Build project by NMake'
- job: build_in_ubuntu_latest
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      mkdir build
      cd build
      cmake .. -G "Unix Makefiles"
      make
      make clean
      cd ..
      rm -rf build/
    displayName: 'Build Makefile by CMake & Build project by GNU Make'